[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
degen_wall = "DEGENvq96VhCR8jawM9ZkBuQtGtFNTsER4ohGPkFBLUt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = './degen_wall-deployer.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/unit/**/*.ts"
